config/routes.rb
TodoMVC::Application.routes.draw do
  resources :todos, except: [:show] do
    collection do
      get :active, to: :index, active: true
      get :completed, to: :index, completed: true
      post :toggle_all
      delete :destroy_completed
    end
  end

  root to: 'todos#index'
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  default_scope { order(:created_at) }

  validates :title, presence: true
  scope :active, -> { where(completed: false) }
  scope :completed, -> { where(completed: true) }

  def title=(title)
    write_attribute(:title, title.try(:strip))
  end

  ##
  # Class methods

  def self.toggle_all
    active.any? ? active.update_all(completed: true) : update_all(completed: false)
  end

  def self.clear_completed
    completed.destroy_all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_filter, only: [:toggle_all, :destroy_completed]
  before_action :set_todos, only: [:index, :toggle_all, :destroy_completed]
  before_action :set_todo, only: [:edit, :update, :destroy]
  respond_to :html, :js

  def index
    respond_with @todos
  end

  def new
    @todo = Todo.new
    respond_with @todo
  end

  def create
    @todo = Todo.new(todo_params)
    flash[:notice] = 'Todo was successfully created.' if @todo.save
    respond_with @todo
  end

  def edit
    respond_with @todo
  end

  def update
    flash[:notice] = 'Todo was successfully updated.' if @todo.update(todo_params)
    respond_with @todo
  end

  def destroy
    flash[:notice] = 'Todo was successfully destroyed.' if @todo.destroy
    respond_with @todo
  end

  def toggle_all
    Todo.toggle_all
    respond_with @todos
  end

  def destroy_completed
    Todo.clear_completed
    respond_with @todos
  end

  private

  def set_filter
    path = request.referer
    return unless path.present?
    params[:active] = true if path.end_with?(active_todos_path)
    params[:completed] = true if path.end_with?(completed_todos_path)
  end

  def set_todos
    @todos = case
             when params[:active] then Todo.active
             when params[:completed] then Todo.completed
             else Todo.all
             end
  end

  def set_todo
    @todo = Todo.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(:title, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def icon_tag(icon)
    content_tag :i, '', class: "fa fa-#{icon}"
  end

  def selected_link_to(*args)
    path = args[1]
    args[2] ||= {}
    args[2][:class] ||= ''
    args[2][:class] += ' selected' if path == request.fullpath
    link_to *args
  end
end

app/views/application/_flashes.html.erb
<div id="flash">
  <% flash.each do |key, value| -%>
    <div id="flash_<%= key %>"><%= value %></div>
  <% end -%>
</div>

app/views/application/_footer.html.slim
footer#info
  p Double-click to edit a todo
  p
    ' Created by
    = link_to 'Thomas Klemm', 'https://github.com/thomasklemm'
  p
    ' Part of
    = link_to 'TodoMVC', 'http://todomvc.com'

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" data-framework="rails">
  <head>
    <meta charset="utf-8" />
    <meta name="ROBOTS" content="NOODP" />
    <title>Rails • TodoMVC</title>
    <%= stylesheet_link_tag :application, :media => 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= yield %>
    <%= render 'footer' %>
    <%= render 'javascript' %>
  </body>
</html>

app/views/todos/_new_todo_form.html.slim
/ new todo form
= form_for Todo.new, remote: true do |f|
  = f.text_field :title, id: 'new-todo', placeholder: 'What needs to be done?', autofocus: true, autocomplete: 'off'

app/views/todos/_todo.html.slim
/ todo partial
= content_tag_for :li, todo, data: { id: todo.id, completed: todo.completed },
  class: ('completed' if todo.completed?) do

  div class='view'

    / complete todo
    = form_for todo, remote: true do |f|
      = f.check_box :completed, class: 'toggle'

    / todo title
    label = todo.title

  / title field
  = form_for todo, remote: true do |f|
    = f.text_field :title, class: 'edit', autocomplete: 'off'

  / destroy todo
  = link_to icon_tag('times'), todo, method: :delete, remote: true, class: 'destroy'

app/views/todos/clear_completed.js.erb
Todo.replaceList('<%= j render(@todos) %>');

app/views/todos/create.js.erb
Todo.create('<%= j render(@todo) %>');

app/views/todos/destroy.js.erb
Todo.destroy(<%= @todo.id %>);

app/views/todos/destroy_completed.js.erb
Todo.replaceList('<%= j render(@todos) %>');

app/views/todos/edit.js.erb
Todo.edit(<%= @todo.id %>, '<%= j render "form" %>');

app/views/todos/index.html.slim
section#todoapp
  header#header
    h1 todos

    / create new todos
    = render 'new_todo_form'

  section#main
    / mark all todos as complete
    = link_to '', toggle_all_todos_path, method: :post, remote: true, id: 'toggle-all'

    / todo list
    = content_tag :ul, id: 'todo-list' do
      = render @todos

  footer#footer
    / active todos count (placeholder)
    span#active-todos-count

    / filter by completed
    ul#filters
      li = selected_link_to 'All', todos_path, remote: true
      li = selected_link_to 'Active', active_todos_path, remote: true
      li = selected_link_to 'Completed', completed_todos_path, remote: true

    / destroy completed todos
    = link_to destroy_completed_todos_path, method: :delete, remote: true, id: 'clear-completed', class: 'hidden' do
      ' Clear completed
      span#completed-todos-count

app/views/todos/index.js.erb
Todo.replaceList('<%= j render(@todos) %>');

app/views/todos/new.js.erb
Todo.new('<%= render "form" %>');

app/views/todos/toggle_all.js.erb
Todo.replaceList('<%= j render(@todos) %>');

app/views/todos/update.js.erb
Todo.update(<%= @todo.id %>, '<%= j render(@todo) %>');